server:
  port: ${SENDER_PORT}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_IP}:${KAFKA_BROKER_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
  datasource:
    url: jdbc:postgresql://${DB_IP}:${DB_PORT}/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

topic:
  queuedStorage: ${TOPIC_NAME}