server:
  port: ${STORAGE_PORT}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_IP}:${KAFKA_BROKER_PORT}
    consumer:
      group-id: "storage-1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  datasource:
    url: jdbc:postgresql://${DB_IP}:${DB_PORT}/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

topic:
  queuedStorage: ${TOPIC_NAME}

storage:
  location: "${STORAGE_LOCATION}"
